-- Supabase migration for BRIDGE TV
-- Run once in Supabase SQL Editor after creating the Auth admin user.
-- Admin UID supplied by project owner: bf8a8fdc-52ae-4626-b47c-5ef802296001

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(btrim(message)) between 1 and 120),
  "user" text not null check (char_length(btrim("user")) between 1 and 32),
  display_name text not null default '',
  sms_type text not null default 'normal'
    check (sms_type in ('normal','vip','glamour','express')),
  source text not null default 'moderator',
  sender_role text not null default 'moderator',
  ts bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  inbox_id bigint,
  repeated boolean not null default false
);

create table if not exists public.inbox (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(btrim(message)) between 1 and 120),
  "user" text not null check (char_length(btrim("user")) between 1 and 32),
  display_name text not null default '',
  sms_type text not null default 'normal'
    check (sms_type in ('normal','vip','glamour','express')),
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  ts bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  approved_at timestamptz,
  rejected_at timestamptz
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

-- Register the designated admin. This will fail if the Auth user doesn't exist.
insert into public.admin_users(user_id)
values ('bf8a8fdc-52ae-4626-b47c-5ef802296001'::uuid)
on conflict do nothing;

alter table public.messages enable row level security;
alter table public.inbox enable row level security;
alter table public.admin_users enable row level security;

-- Remove broad/default client grants before adding least-privilege grants.
revoke all on public.messages, public.inbox, public.admin_users from anon, authenticated;
grant select on public.messages to anon, authenticated;
grant insert (message, "user", display_name, sms_type) on public.inbox to anon;
grant select, update, delete on public.inbox to authenticated;
grant insert, update, delete on public.messages to authenticated;

-- Identity sequences require explicit usage for inserts.
grant usage, select on sequence public.inbox_id_seq to anon;
grant usage, select on sequence public.inbox_id_seq to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

drop policy if exists "Public can read published messages" on public.messages;
create policy "Public can read published messages"
on public.messages for select to anon, authenticated
using (true);

drop policy if exists "Visitors can submit pending inbox" on public.inbox;
create policy "Visitors can submit pending inbox"
on public.inbox for insert to anon
with check (
  status = 'pending'
  and approved_at is null
  and rejected_at is null
  and char_length(btrim(message)) between 1 and 120
  and char_length(btrim("user")) between 1 and 32
  and sms_type in ('normal','vip','glamour','express')
);

drop policy if exists "Admins read inbox" on public.inbox;
create policy "Admins read inbox"
on public.inbox for select to authenticated
using ((select private.is_admin()));

drop policy if exists "Admins update inbox" on public.inbox;
create policy "Admins update inbox"
on public.inbox for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "Admins delete inbox" on public.inbox;
create policy "Admins delete inbox"
on public.inbox for delete to authenticated
using ((select private.is_admin()));

drop policy if exists "Admins publish messages" on public.messages;
create policy "Admins publish messages"
on public.messages for insert to authenticated
with check ((select private.is_admin()));

drop policy if exists "Admins update messages" on public.messages;
create policy "Admins update messages"
on public.messages for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "Admins delete messages" on public.messages;
create policy "Admins delete messages"
on public.messages for delete to authenticated
using ((select private.is_admin()));

-- Enable Realtime for public overlay and admin inbox listeners.
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.inbox;
exception when duplicate_object then null;
end $$;

-- Reminder: admin_users intentionally has no client grants/policies.
-- Do not expose Supabase service_role/secret keys in GitHub Pages.
